import { z } from "zod";
import VALIDATION from "../VALIDATIONS";

export const villaDefaultValues = {
  villa: {
    complexName: undefined,
    villaNo: undefined,
    emirate: undefined,
    area: undefined,
    suburb: undefined,
    street: undefined,
    docType: undefined,
    docNo: undefined,
    docDate: undefined,
    pieceNo: undefined,
    basinNo: undefined,
    waterMeter: undefined,
    electricityMeter: undefined,
    note: undefined,
    assetsId: null,
    value: undefined,
    villaAccountId: null,
    costCenterId: null,
    accountBankVillaId: null,
    cashAccountId: null,
    insuranceAccountId: null,
    lessorId: null,
    roomState: undefined,
    roomCount: undefined,
    serviceRoomCount: undefined,
    bathRoomCount: undefined,
    otherRoomCount: undefined,
    balconyCount: undefined,
    floorCount: undefined,
    stairsInternal: undefined,
    areaUnit: undefined,
    landArea: undefined,
    landAreaBuilding: undefined,
    finishingState: undefined,
    securitySystem: undefined,
    securityType: undefined,
    wall: undefined,
    wallState: undefined,
    lightingCount: undefined,
    parkingCount: undefined,
    parkingArea: undefined,
    parkingShaded: undefined,
    poolCount: undefined,
    poolState: undefined,
    poolSystem: undefined,
    playGroundCount: undefined,
    playGroundArea: undefined,
    gardenCount: undefined,
    gardenArea: undefined,
    gardenState: undefined,
  },
  villaRentalPrices: [],
  villaSellingPrices: []
}

const villaSchema = z.object({
  complexName: VALIDATION.OPTIONAL_STRING,
  villaNo: VALIDATION.OPTIONAL_STRING,
  emirate: VALIDATION.OPTIONAL_STRING,
  area: VALIDATION.OPTIONAL_STRING,
  suburb: VALIDATION.OPTIONAL_STRING,
  street: VALIDATION.OPTIONAL_STRING,
  docType: VALIDATION.OPTIONAL_STRING,
  docNo: VALIDATION.OPTIONAL_STRING,
  docDate: VALIDATION.OPTIONAL_STRING,
  pieceNo: VALIDATION.OPTIONAL_STRING,
  basinNo: VALIDATION.OPTIONAL_STRING,
  waterMeter: VALIDATION.OPTIONAL_STRING,
  electricityMeter: VALIDATION.OPTIONAL_STRING,
  note: VALIDATION.OPTIONAL_STRING,
  assetsId: VALIDATION.OPTIONAL_STRING,
  value: VALIDATION.OPTIONAL_STRING,
  villaAccountId: VALIDATION.OPTIONAL_STRING,
  costCenterId: VALIDATION.OPTIONAL_STRING,
  accountBankVillaId: VALIDATION.OPTIONAL_STRING,
  cashAccountId: VALIDATION.OPTIONAL_STRING,
  insuranceAccountId: VALIDATION.OPTIONAL_STRING,
  lessorId: VALIDATION.OPTIONAL_STRING,
  roomState: VALIDATION.OPTIONAL_STRING,
  roomCount: VALIDATION.OPTIONAL_STRING,
  serviceRoomCount: VALIDATION.OPTIONAL_STRING,
  bathRoomCount: VALIDATION.OPTIONAL_STRING,
  otherRoomCount: VALIDATION.OPTIONAL_STRING,
  balconyCount: VALIDATION.OPTIONAL_STRING,
  floorCount: VALIDATION.OPTIONAL_STRING,
  stairsInternal: VALIDATION.OPTIONAL_STRING,
  areaUnit: VALIDATION.OPTIONAL_STRING,
  landArea: VALIDATION.OPTIONAL_STRING,
  landAreaBuilding: VALIDATION.OPTIONAL_STRING,
  finishingState: VALIDATION.OPTIONAL_STRING,
  securitySystem: VALIDATION.OPTIONAL_STRING,
  securityType: VALIDATION.OPTIONAL_STRING,
  wall: VALIDATION.OPTIONAL_STRING,
  wallState: VALIDATION.OPTIONAL_STRING,
  lightingCount: VALIDATION.OPTIONAL_STRING,
  parkingCount: VALIDATION.OPTIONAL_STRING,
  parkingArea: VALIDATION.OPTIONAL_STRING,
  parkingShaded: VALIDATION.OPTIONAL_STRING,
  poolCount: VALIDATION.OPTIONAL_STRING,
  poolState: VALIDATION.OPTIONAL_STRING,
  poolSystem: VALIDATION.OPTIONAL_STRING,
  playGroundCount: VALIDATION.OPTIONAL_STRING,
  playGroundArea: VALIDATION.OPTIONAL_STRING,
  gardenCount: VALIDATION.OPTIONAL_STRING,
  gardenArea: VALIDATION.OPTIONAL_STRING,
  gardenState: VALIDATION.OPTIONAL_STRING,
})

const villaRentalPriceSchema = z.object({
  price: VALIDATION.OPTIONAL_NUMBER,
  date: VALIDATION.OPTIONAL_DATE,
  currencyId: VALIDATION.OPTIONAL_STRING,
  note: VALIDATION.OPTIONAL_STRING,
  // number: VALIDATION.OPTIONAL_NUMBER
});

const villaSellingPriceSchema = z.object({
  price: VALIDATION.OPTIONAL_NUMBER,
  date: VALIDATION.OPTIONAL_DATE,
  currencyId: VALIDATION.OPTIONAL_STRING,
  note: VALIDATION.OPTIONAL_STRING,
  // number: VALIDATION.OPTIONAL_NUMBER
});


export const villaValidationSchema = () => z.object({
  villa: villaSchema,
  villaRentalPrices: z.array(villaRentalPriceSchema).optional(),
  villaSellingPrices: z.array(villaSellingPriceSchema).optional(),
});

