version: '3.8'
services:
  dashboard:
    env_file:
      - ./.env
    build: .

  nginx:
    image: nginx:latest
    ports:
      - '3002:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - dashboard
