// ===============  NOTE: for now just register a new function for new report ==============
// ===============  GET: cheque report data ==============
export const getChequeReportData = () => {}
// ===============  GET: changes flat rent price ==============
export const getChangesFlatRentPricingReportData = () => {}
// ===============  GET: changes flat sale price ==============
export const getChangesFlatSalePricingReportData = () => {}
// ===============  GET: building schema report data ==============
export const getBuildingSchemaReportData = () => {}
// ===============  GET: announcement report data ==============
export const getCollectionChqReportData = () => {}
// ===============  GET: announcement report data ==============
export const getComplaintsReportData = () => {}
// ===============  GET: announcement report data ==============
export const getContractChequeReportData = () => {}
// ===============  GET: announcement report data ==============
export const getContractCycleReportData = () => {}
// ===============  GET: announcement report data ==============
export const getContractNearToExpiredReportData = () => {}
// ===============  GET: announcement report data ==============
export const getContractPaymentsReportData = () => {}
// ===============  GET: announcement report data ==============
export const getContractDepositReportData = () => {}
// ===============  GET: announcement report data ==============
export const getExpiredContractReportData = () => {}
// ===============  GET: announcement report data ==============
export const getContractReportData = () => {}
// ===============  GET: announcement report data ==============
export const getCostCenterTrialBalanceReportData = () => {}
// ===============  GET: announcement report data ==============
export const getCostCenterGeneralLedgerReportData = () => {}
// ===============  GET: announcement report data ==============
export const getCreditorsAgesReportData = () => {}
// ===============  GET: announcement report data ==============
export const getCustomersAccountStatementReportData = () => {}
// ===============  GET: announcement report data ==============
export const getDueNotePaperReportData = () => {}
// ===============  GET: announcement report data ==============
export const getEarningRentalIncomeEarnedReportData = () => {}
// ===============  GET: announcement report data ==============
export const getGeneralLedgerReportData = () => {}
// ===============  GET: announcement report data ==============
export const getJournalLedgerReportData = () => {}
// ===============  GET: announcement report data ==============
export const getLeasedLandsReportData = () => {}
// ===============  GET: announcement report data ==============
export const getLeasedParkingReportData = () => {}
// ===============  GET: announcement report data ==============
export const getLeasedPropertyActivityReportData = () => {}
// ===============  GET: announcement report data ==============
export const getLeasedUnitsReportData = () => {}
// ===============  GET: announcement report data ==============
export const getLeasedVillasReportData = () => {}
// ===============  GET: announcement report data ==============
export const getWorkerReportData = () => {}
// ===============  GET: announcement report data ==============
// ===============  GET: announcement report data ==============
export const getAnnouncementReportData = () => {}