import VALIDATION from "@/helpers/VALIDATIONS"
import { z } from "zod"

export const contractPatternDefaultValues = {
  contractType: 1,
  name: "",
  listName: "",
  shortcutKey: "",
  genEntries: true,
  autoGenEntries: false,
  autoTransferEntry: false,
  recordDateCreated: 0,
  newContractWithoutTerminating: false,
  insuranceRequired: false,
  defaultRevenueAccountId: null,
  defaultCommissionFromClientAccountId: null,
  defaultCommissionFromOwnerAccountId: null,
  defaultCommissionFromClientPercentage: 5.0,
  assetsType: 1,
  moveCostCenterWithRevenue: 0,
  moveCostCenterWithTenant: 0,
  moveCostCenterWithInsuranceRevenue: 0,
  moveCostCenterWithPriceRevenue: 0,
  moveCostCenterWithIntentionRatifying: 0,
  moveCostCenterWithOtherFee: 0,
  moveCostCenterWithCommissionClient: 0,
  moveCostCenterWithCommissionOwner: 0,
  moveCostCenterWithContractFinesTerminating: 0,
  moveCostCenterWithDecisivenessGranted: 0,
  moveCostCenterWithContractProceedsRerminating: 0,
  contractTerms: "",
  folderDefaultPrinting: "",
  folderPrintCommunications: "",
  folderPrintClearance: "",
  sms: "",
  ltnname: "",
  listLtnname: "",
  code: null,
  defaultContractPriceRevenueAccountId: null,
  defaultContractRatificationRevenueAccountId: null,
  defaultFinesRevenueAccountId: null,
  defaultFeeRevenueAccountId: null,
  defaultVatAccountId: null,
  defaultDiscountAccountId: null,
  defaultCommission_FromClient_Percentage: "",
  defaultInsuranceAccountId: null,
  defaultFeesAccount1: null,
  defaultFeesAccount2: null,
  defaultFeesAccount3: null,
  defaultFeesAccount4: null,
  defaultFeesAccount5: null,
  defaultFeesAccount6: null,
  defaultFeesAccount7: null,
  defaultFeesAccount8: null,
  defaultFeesAccount9: null,
  defaultFeesAccount0: null,
}

export const contractPatternValidationSchema = () => z.object({
  name: VALIDATION.NON_EMPTY_STRING,
  ltnname: VALIDATION.OPTIONAL_STRING,
  listLtnname: VALIDATION.OPTIONAL_STRING,
  code: VALIDATION.NON_NEGATIVE_NUMBER,
  contractType: VALIDATION.NON_NEGATIVE_NUMBER,
  listName: VALIDATION.OPTIONAL_STRING,
  shortcutKey: VALIDATION.OPTIONAL_STRING,
  genEntries: VALIDATION.OPTIONAL_BOOLEAN,
  autoGenEntries: VALIDATION.OPTIONAL_BOOLEAN,
  autoTransferEntry: VALIDATION.OPTIONAL_BOOLEAN,
  recordDateCreated: VALIDATION.OPTIONAL_NUMBER,
  newContractWithoutTerminating: VALIDATION.OPTIONAL_BOOLEAN,
  insuranceRequired: VALIDATION.OPTIONAL_BOOLEAN,
  defaultRevenueAccountId: VALIDATION.OPTIONAL_STRING,
  defaultCommissionFromClientAccountId: VALIDATION.OPTIONAL_STRING,
  defaultCommissionFromOwnerAccountId: VALIDATION.OPTIONAL_STRING,
  defaultCommissionFromClientPercentage: VALIDATION.OPTIONAL_NUMBER,
  assetsType: VALIDATION.OPTIONAL_NUMBER,
  moveCostCenterWithRevenue: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithTenant: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithInsuranceRevenue: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithPriceRevenue: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithIntentionRatifying: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithOtherFee: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithCommissionClient: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithCommissionOwner: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithContractFinesTerminating: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithDecisivenessGranted: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  moveCostCenterWithContractProceedsRerminating: VALIDATION.OPTIONAL_NUMBER, // { "debit": false, "credit": false },
  contractTerms: VALIDATION.OPTIONAL_STRING,
  folderDefaultPrinting: VALIDATION.OPTIONAL_STRING,
  folderPrintCommunications: VALIDATION.OPTIONAL_STRING,
  folderPrintClearance: VALIDATION.OPTIONAL_STRING,
  sms: VALIDATION.OPTIONAL_STRING,
  defaultContractPriceRevenueAccountId: VALIDATION.OPTIONAL_STRING,
  defaultContractRatificationRevenueAccountId: VALIDATION.OPTIONAL_STRING,
  defaultFinesRevenueAccountId: VALIDATION.OPTIONAL_STRING,
  defaultFeeRevenueAccountId: VALIDATION.OPTIONAL_STRING,
  defaultVatAccountId: VALIDATION.OPTIONAL_STRING,
  defaultDiscountAccountId: VALIDATION.OPTIONAL_STRING,
  defaultCommission_FromClient_Percentage: VALIDATION.OPTIONAL_STRING,
  defaultInsuranceAccountId: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount1: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount2: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount3: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount4: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount5: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount6: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount7: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount8: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount9: VALIDATION.OPTIONAL_STRING,
  defaultFeesAccount0: VALIDATION.OPTIONAL_STRING,
})