import VALIDATION from "@/helpers/VALIDATIONS"
import { z } from "zod"

export const voucherPatternDefaultValues = {
  code: null,
  name: "",
  ltnname: "",
  listName: "",
  defaultAccountId: null,
  shortcutKey: "",
  genEntries: true,
  autoGenEntries: false,
  autoTransferEntry: false,
  generateRecords: false,
  showContractField: false,
  showContractCostCenter: false,
  requiredCostCenter: false,
  requiredStatement: false,
  defaultPrintFolderPath: "",
  showDebitField: false,
  showCreditField: false,
  debitFieldLabel: "",
  creditFieldLabel: "",
  showCurrency: false,
  showCostCenter: false,
  showNote: false,
  oddTableColor: "",
  evenTableColor: "",
  sms: "",
}

export const voucherPatternValidationSchema = () => z.object({
  code: VALIDATION.NON_NEGATIVE_NUMBER,
  name: VALIDATION.NON_EMPTY_STRING,
  ltnname: VALIDATION.OPTIONAL_STRING,
  listName: VALIDATION.OPTIONAL_STRING,
  defaultAccountId: VALIDATION.OPTIONAL_UUID,
  shortcutKey: VALIDATION.OPTIONAL_STRING,
  genEntries: VALIDATION.OPTIONAL_BOOLEAN,
  autoGenEntries: VALIDATION.OPTIONAL_BOOLEAN,
  autoTransferEntry: VALIDATION.OPTIONAL_BOOLEAN,
  generateRecords: VALIDATION.OPTIONAL_BOOLEAN,
  showContractField: VALIDATION.OPTIONAL_BOOLEAN,
  showContractCostCenter: VALIDATION.OPTIONAL_BOOLEAN,
  requiredCostCenter: VALIDATION.OPTIONAL_BOOLEAN,
  requiredStatement: VALIDATION.OPTIONAL_BOOLEAN,
  defaultPrintFolderPath: VALIDATION.OPTIONAL_STRING,
  showDebitField: VALIDATION.OPTIONAL_BOOLEAN,
  showCreditField: VALIDATION.OPTIONAL_BOOLEAN,
  debitFieldLabel: VALIDATION.OPTIONAL_STRING,
  creditFieldLabel: VALIDATION.OPTIONAL_STRING,
  showCurrency: VALIDATION.OPTIONAL_BOOLEAN,
  showCostCenter: VALIDATION.OPTIONAL_BOOLEAN,
  showNote: VALIDATION.OPTIONAL_BOOLEAN,
  oddTableColor: VALIDATION.OPTIONAL_STRING,
  evenTableColor: VALIDATION.OPTIONAL_STRING,
  sms: VALIDATION.OPTIONAL_STRING,
})