import { z } from "zod"

export const buildingDefaultValues = {
  apartment_count: 0,
  apartment_floor: 0,
  area: null,
  bank_account_number: null,
  basin_number: null,
  bond_date: null,
  bond_number: null,
  bond_type: null,
  building_bank_account_id: null,
  building_cash_account_id: null,
  building_cheque_account_id: null,
  building_cost: null,
  building_deposit_account_id: null,
  building_discount_account_id: null,
  building_insurance_account_id: null,
  building_number: null,
  building_receipt: null,
  building_revenue_account_id: null,
  city: null,
  commission_expense_account_id: null,
  commission_rate: null,
  created_at: null,
  customers_main_account_id: null,
  deferred_vat_account_id: null,
  display: null,
  emirate: null,
  entry_commission_from_owner_account_id: null,
  entry_commission_rate: null,
  entry_landlord_account_id: null,
  entry_revenue_account_id: null,
  entry_vat_account_id: null,
  entry_vat_rate: null,
  investment_end_date: null,
  investment_gen_entries: null,
  investment_owner_account_id: null,
  investment_start_date: null,
  investment_value: null,
  lessor_id: null,
  ltnname: null,
  mezzanine_count: 0,
  mezzanine_floor: 0,
  name: null,
  note: null,
  office_count: 0,
  office_floor: 0,
  owner_account_id: null,
  owner_balance: null,
  owner_id: null,
  owner_tax_account_id: null,
  parking_count: 0,
  parking_floor: 0,
  part_number: null,
  penthouse_count: 0,
  penthouse_floor: 0,
  purchase_date: null,
  realestate_company_account_id: null,
  received_account_id: null,
  received_amount: null,
  received_date: null,
  received_note: null,
  renters_insurance: null,
  shop_count: 0,
  statement: null,
  store_count: 0,
  street: null,
  suburb: null,
  supplier_account_id: null,
  tenants: null,
  underground_parking: null,
  vat_account_id: null,
  warehouse_count: 0,
}


export const buildingValidationSchema = z.object({
  name: z.string().min(1, { message: "building name is required" }),
})