// export const BILL_PATTERN_general = [
//   { label: "code", name: "code", type: "number", required: false },
//   { label: "name", name: "name", type: "text", required: false },
//   { label: "ltnname", name: "ltnname", type: "text", required: false },
//   { label: "number", name: "number", type: "number", required: false },
//   FIELDS_STRUCTURE.selectField({
//     label: "bill_type",
//     name: "bill_type",
//     list: SELECT_LISTS("bill_pattern_bill_type"),
//   }),
//   { label: "note", name: "note", type: "text", required: false },

//   {
//     label: "currency_id",
//     name: "currency_id",
//     type: "uuid",
//     required: true,
//     is_ref: true,
//     ref_table: "currency",
//     ref_col: "id",
//     hideValue: true,
//   },
//   FIELDS_STRUCTURE.switchField({
//     label: "barcode_bill",
//     name: "barcode_bill",
//   }),
// ];
// export const BILL_PATTERN_accounts = [
//   {
//     label: "default_store_id",
//     name: "default_store_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "store",
//     ref_col: "id",
//   },
//   {
//     label: "cost_center_id",
//     name: "cost_center_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "cost_center",
//     ref_col: "id",
//   },
//   {
//     label: "material_account_id",
//     name: "material_account_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "account",
//     ref_col: "id",
//   },
//   {
//     label: "cash_account_id",
//     name: "cash_account_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "account",
//     ref_col: "id",
//   },
//   {
//     label: "discount_account_id",
//     name: "discount_account_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "account",
//     ref_col: "id",
//   },
//   {
//     label: "extra_account_id",
//     name: "extra_account_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "account",
//     ref_col: "id",
//   },

//   FIELDS_STRUCTURE.selectField({
//     label: "payment_method",
//     name: "payment_method",
//     list: SELECT_LISTS("bill_pattern_payment_methods"),
//   }),

//   {
//     label: "active_perpetual_inventory",
//     name: "active_perpetual_inventory",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "stock_account_id",
//     name: "stock_account_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "account",
//     ref_col: "id",
//   },
//   {
//     label: "calculate_sale_cost_center_id",
//     name: "calculate_sale_cost_center_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "calculate_sale_cost_center",
//     ref_col: "id",
//   },

//   {
//     label: "vat_account_id",
//     name: "vat_account_id",
//     type: "uuid",
//     required: false,
//     is_ref: true,
//     ref_table: "account",
//     ref_col: "id",
//   },
//   {
//     label: "vat_percentage",
//     name: "vat_percentage",
//     type: "number",
//   },
//   {
//     label: "use_vat_account_from_customer_card",
//     name: "use_vat_account_from_customer_card",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
// ];
// export const BILL_PATTERN_entries = [
//   {
//     label: "post_to_store",
//     name: "post_to_store",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "post_to_store_auto",
//     name: "post_to_store_auto",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "generate_entries",
//     name: "generate_entries",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "auto_generate_entries",
//     name: "auto_generate_entries",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "post_generate_entries_auto",
//     name: "post_generate_entries_auto",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "deleting_entry_depending_on_materials",
//     name: "deleting_entry_depending_on_materials",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "possibility_of_changing_materials_account",
//     name: "possibility_of_changing_materials_account",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "calculate_vat_after_discount_and_extra_value_to_the_invoice",
//     name: "calculate_vat_after_discount_and_extra_value_to_the_invoice",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "merge_repeated_materials",
//     name: "merge_repeated_materials",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "required_customer_entry",
//     name: "required_customer_entry",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "required_cost_center_entry",
//     name: "required_cost_center_entry",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "required_category_entry",
//     name: "required_category_entry",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "show_alert_on_navigate_output",
//     name: "show_alert_on_navigate_output",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "dont_save_when_navigate_output",
//     name: "dont_save_when_navigate_output",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "show_average_price_check_message_after_adding_modifying",
//     name: "show_average_price_check_message_after_adding_modifying",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
// ];
// export const BILL_PATTERN_options = [
//   {
//     label: "bill_affected_the_pricing_of_materials",
//     name: "bill_affected_the_pricing_of_materials",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "pricing_of_materials",
//     name: "pricing_of_materials",
//     type: "number",
//     required: false,
//   },
//   { label: "menu", name: "menu", type: "text", required: false },
//   {
//     label: "table_color1",
//     name: "table_color1",
//     type: "color",
//     required: false,
//   },
//   {
//     label: "table_color2",
//     name: "table_color2",
//     type: "color",
//     required: false,
//   },
// ];
// export const BILL_PATTERN_bill_details = [];
// export const BILL_PATTERN_references = [
//   {
//     label: "show_references_field",
//     name: "show_references_field",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "required_reference_field",
//     name: "required_reference_field",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "dont_show_expired_field",
//     name: "dont_show_expired_field",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "lock_bill_when_loading_references",
//     name: "lock_bill_when_loading_references",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },
//   {
//     label: "allow_partial_load",
//     name: "allow_partial_load",
//     type: "checkbox",
//     key: "switch",
//     required: false,
//   },

//   { label: "references", name: "references", type: "jsonb[]", required: false },
// ];